# Generated by Django 3.1.4 on 2020-12-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_auto_20201211_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('availibility_for_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1)),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra')], max_length=50)),
                ('district', models.CharField(choices=[('nanded', 'nanded'), ('nagpur', 'nagpur')], max_length=50)),
                ('city', models.CharField(choices=[('vishnupuri', 'vishnupuri')], max_length=50)),
                ('home_address', models.TextField(blank=True, max_length=200)),
                ('profile_image', models.ImageField(default='profile.jpg', upload_to='profiles')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_props', models.IntegerField()),
                ('rent_amount', models.IntegerField()),
                ('type', models.CharField(choices=[('room', 'Room Basis'), ('cot', 'Cot Basis')], max_length=50)),
                ('image', models.ImageField(default='propdef.jpg', upload_to='properties')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mainapp.owner')),
            ],
        ),
    ]
